// script.js (Siap-tempel)
// Module-based script — dashboard utama yang terhubung ke Firebase Auth + Firestore
// Pastikan Anda memanggil file ini dengan: <script type="module" src="script.js"></script>

import { initializeApp } from "https://www.gstatic.com/firebasejs/11.0.1/firebase-app.js";
import {
  getAuth,
  onAuthStateChanged,
  signOut
} from "https://www.gstatic.com/firebasejs/11.0.1/firebase-auth.js";
import {
  getFirestore,
  collection,
  query,
  where,
  getDocs,
  addDoc,
  updateDoc,
  deleteDoc,
  doc,
  getDoc,
  serverTimestamp
} from "https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js";

/* ===========================
   KONFIGURASI FIREBASE (project: dashboard-png)
   =========================== */
const firebaseConfig = {
  apiKey: "AIzaSyClRE2w0JeSj81gkccPC1au3hG8lQYbLzw",
  authDomain: "dashboard-png.firebaseapp.com",
  projectId: "dashboard-png",
  storageBucket: "dashboard-png.firebasestorage.app",
  messagingSenderId: "121187805643",
  appId: "1:121187805643:web:6c67dd587abbe09f782e4e",
  measurementId: "G-N5MV2N5X33"
};

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);

/* ===========================
   SELECTOR & STATE
   =========================== */
// Sections / UI
const menuItems = document.querySelectorAll('.menu-item');
const contentSections = document.querySelectorAll('.content-section');
const menuToggle = document.getElementById('menuToggle');
const sidebar = document.querySelector('.sidebar');
const pageTitle = document.getElementById('pageTitle');

// Table bodies (pastikan id ada di HTML)
const hatoribetTableBody = document.getElementById('hatoribetTableBody');
const livitotoTableBody = document.getElementById('livitotoTableBody');
const hmd29TableBody = document.getElementById('hmd29TableBody');

const staffHatoribetCount = document.getElementById('staffHatoribetCount');
const staffLivitotoCount = document.getElementById('staffLivitotoCount');
const staffHmd29Count = document.getElementById('staffHmd29Count');

// Modal elements (jika ada pada HTML)
const modal = document.getElementById('staffModal');
const staffForm = document.getElementById('staffForm');
const cancelBtn = document.getElementById('cancelBtn');
const modalTitle = document.getElementById('modalTitle');
const staffIdInput = document.getElementById('staffId');
const editModeInput = document.getElementById('editMode');

// activity list etc
const activityList = document.getElementById('activityList');

// current user state
let currentUser = null;
let currentUserDoc = null; // doc from 'users' collection (contains role, canEdit)
let isAdminOrCanEdit = false;

/* ===========================
   AUTH: cek status login
   =========================== */
onAuthStateChanged(auth, async (user) => {
  if (!user) {
    // belum login -> kembali ke halaman login
    window.location.href = 'index.html';
    return;
  }

  currentUser = user;
  // ambil doc user di koleksi 'users' untuk dapatkan role & flag canEdit
  try {
    const userDocRef = doc(db, 'users', user.uid);
    const userSnap = await getDoc(userDocRef);
    if (userSnap.exists()) {
      currentUserDoc = userSnap.data();
    } else {
      // jika belum ada doc (kemungkinan register belum membuat doc), buat default doc
      const defaultRole = (user.email === 'admin@company.com') ? 'admin' : 'staff';
      await addDoc(collection(db, 'users'), { // created with autogenerated id if not created by register flow
        uid: user.uid,
        email: user.email,
        username: user.email.split('@')[0],
        role: defaultRole,
        canEdit: defaultRole === 'admin',
        createdAt: serverTimestamp()
      });
      // coba ambil lagi (sederhana)
      const q = query(collection(db, 'users'), where('uid', '==', user.uid));
      const qSnap = await getDocs(q);
      if (!qSnap.empty) currentUserDoc = qSnap.docs[0].data();
    }
  } catch (err) {
    console.warn('Gagal ambil user doc:', err.message);
    // fallback ke minimal info
    currentUserDoc = { email: user.email, username: user.email.split('@')[0], role: (user.email === 'admin@company.com') ? 'admin' : 'staff', canEdit: user.email === 'admin@company.com' };
  }

  isAdminOrCanEdit = !!(currentUserDoc && currentUserDoc.canEdit);

  // Update header/profile UI (jaga sesuai elemen di HTML)
  try {
    const userProfileImg = document.querySelector('.user-profile img');
    const userProfileName = document.querySelector('.user-profile span');
    if (userProfileImg) userProfileImg.src = currentUserDoc.avatar || `https://ui-avatars.com/api/?name=${encodeURIComponent(currentUserDoc.username)}&background=0366d6&color=fff`;
    if (userProfileName) userProfileName.textContent = currentUserDoc.username || currentUser.email.split('@')[0];
    const userEmailElem = document.getElementById('userEmail');
    if (userEmailElem) userEmailElem.textContent = currentUser.email;
  } catch (e) { /* ignore */ }

  // aktifkan event dashboard & load data
  initDashboardEvents();
  await loadAllStaff();
  await loadActivities();
  updateStats();
  applyPermissionsUI();
});

/* ===========================
   Logout helper
   =========================== */
async function logout() {
  await signOut(auth);
  window.location.href = 'index.html';
}

/* ===========================
   NAVIGATION / UI HELPERS
   =========================== */
function initDashboardEvents() {
  // menu items
  menuItems.forEach(item => {
    item.addEventListener('click', function () {
      const targetContent = this.getAttribute('data-content');
      menuItems.forEach(mi => mi.classList.remove('active'));
      this.classList.add('active');
      contentSections.forEach(section => section.classList.remove('active'));
      const el = document.getElementById(`${targetContent}-content`);
      if (el) el.classList.add('active');

      const menuText = this.querySelector('span')?.textContent || '';
      if (pageTitle) pageTitle.textContent = menuText;
      // save active menu
      localStorage.setItem('activeMenu', targetContent);
    });
  });

  // menu toggle
  if (menuToggle) menuToggle.addEventListener('click', () => sidebar.classList.toggle('collapsed'));

  // logout btn in header
  const logoutBtn = document.getElementById('logoutBtn');
  if (logoutBtn) logoutBtn.addEventListener('click', logout);

  // modal open buttons (assuming existence of buttons with ids)
  const tambahStaffHatoribet = document.getElementById('tambahStaffHatoribet');
  const tambahStaffLivitoto = document.getElementById('tambahStaffLivitoto');
  const tambahStaffHmd29 = document.getElementById('tambahStaffHmd29');

  if (tambahStaffHatoribet) tambahStaffHatoribet.addEventListener('click', () => openStaffModal('hatoribet'));
  if (tambahStaffLivitoto) tambahStaffLivitoto.addEventListener('click', () => openStaffModal('livitoto'));
  if (tambahStaffHmd29) tambahStaffHmd29.addEventListener('click', () => openStaffModal('hmd29'));

  if (cancelBtn) cancelBtn.addEventListener('click', closeStaffModal);

  // staffForm submit (tambah/edit)
  if (staffForm) staffForm.addEventListener('submit', handleStaffFormSubmit);

  // restore active menu if any
  const activeMenu = localStorage.getItem('activeMenu');
  if (activeMenu) {
    const target = document.querySelector(`.menu-item[data-content="${activeMenu}"]`);
    if (target) target.click();
  }
}

/* ===========================
   PERMISSIONS: tampilkan/SEMBUNYIKAN tombol admin-only
   =========================== */
function applyPermissionsUI() {
  // elemen dengan class .admin-only atau tombol .btn-edit .btn-delete
  const adminOnlyEls = document.querySelectorAll('.admin-only');
  adminOnlyEls.forEach(el => {
    el.style.display = isAdminOrCanEdit ? '' : 'none';
  });

  const restrictedButtons = document.querySelectorAll('.btn-edit, .btn-delete');
  restrictedButtons.forEach(btn => {
    btn.style.display = isAdminOrCanEdit ? '' : 'none';
  });
}

/* ===========================
   FIRESTORE: STAFF CRUD
   Struktur dokumen `staff`:
   {
     name, inisial, tanggalJoin, idAdmin, gmail, bank, noRekGaji, namaRekGaji,
     tanggalLahir, gedung, noKamar, masaKerja, department, createdAt
   }
   =========================== */

async function addStaffToFirestore(staffObj) {
  // staffObj must contain department field
  staffObj.createdAt = serverTimestamp();
  const ref = await addDoc(collection(db, 'staff'), staffObj);
  return ref.id;
}

async function updateStaffInFirestore(docId, staffObj) {
  const staffRef = doc(db, 'staff', docId);
  await updateDoc(staffRef, { ...staffObj, updatedAt: serverTimestamp() });
}

async function deleteStaffFromFirestore(docId) {
  const staffRef = doc(db, 'staff', docId);
  await deleteDoc(staffRef);
}

/* ===========================
   LOAD STAFF: ambil semua staff per department
   =========================== */
async function loadAllStaff() {
  try {
    // ambil semua doc dari koleksi 'staff'
    const q = query(collection(db, 'staff'));
    const snapshot = await getDocs(q);
    const staffList = snapshot.docs.map(d => ({ id: d.id, ...d.data() }));

    // pisahkan per department
    const hatoribet = staffList.filter(s => s.department === 'hatoribet');
    const livitoto = staffList.filter(s => s.department === 'livitoto');
    const hmd29 = staffList.filter(s => s.department === 'hmd29');

    renderStaffTable(hatoribetTableBody, hatoribet);
    renderStaffTable(livitotoTableBody, livitoto);
    renderStaffTable(hmd29TableBody, hmd29);

    // update stats
    if (staffHatoribetCount) staffHatoribetCount.textContent = String(hatoribet.length);
    if (staffLivitotoCount) staffLivitotoCount.textContent = String(livitoto.length);
    if (staffHmd29Count) staffHmd29Count.textContent = String(hmd29.length);
    // total if exists: find element with .stat-number (first)
    const totalEl = document.querySelector('.stat-number');
    if (totalEl) {
      const total = hatoribet.length + livitoto.length + hmd29.length;
      totalEl.textContent = String(total);
    }

    applyPermissionsUI();
  } catch (err) {
    console.error('Gagal load staff:', err.message);
  }
}

/* ===========================
   RENDER TABLE HELPER
   =========================== */
function renderStaffTable(tbodyEl, list) {
  if (!tbodyEl) return;
  tbodyEl.innerHTML = '';
  list.forEach(item => {
    const tr = document.createElement('tr');

    // Create cells in same order as your HTML table header
    const nameTd = document.createElement('td');
    nameTd.textContent = item.name || item.username || item.namaStaff || '';
    tr.appendChild(nameTd);

    const inisialTd = document.createElement('td');
    inisialTd.textContent = item.inisial || '';
    tr.appendChild(inisialTd);

    const tanggalJoinTd = document.createElement('td');
    tanggalJoinTd.textContent = item.tanggalJoin || '';
    tr.appendChild(tanggalJoinTd);

    const idAdminTd = document.createElement('td');
    idAdminTd.textContent = item.idAdmin || '';
    tr.appendChild(idAdminTd);

    const gmailTd = document.createElement('td');
    gmailTd.textContent = item.gmail || item.email || '';
    tr.appendChild(gmailTd);

    const bankTd = document.createElement('td');
    bankTd.textContent = item.bank || '';
    tr.appendChild(bankTd);

    const noRekTd = document.createElement('td');
    noRekTd.textContent = item.noRekGaji || '';
    tr.appendChild(noRekTd);

    const namaRekTd = document.createElement('td');
    namaRekTd.textContent = item.namaRekGaji || '';
    tr.appendChild(namaRekTd);

    const tglLahirTd = document.createElement('td');
    tglLahirTd.textContent = item.tanggalLahir || '';
    tr.appendChild(tglLahirTd);

    const gedungTd = document.createElement('td');
    gedungTd.textContent = item.gedung || '';
    tr.appendChild(gedungTd);

    const noKamarTd = document.createElement('td');
    noKamarTd.textContent = item.noKamar || '';
    tr.appendChild(noKamarTd);

    const masaKerjaTd = document.createElement('td');
    masaKerjaTd.textContent = item.masaKerja || '';
    tr.appendChild(masaKerjaTd);

    // Aksi
    const aksiTd = document.createElement('td');
    // detail button
    const detailBtn = document.createElement('button');
    detailBtn.className = 'btn btn-detail';
    detailBtn.textContent = 'Detail';
    detailBtn.addEventListener('click', () => openDetailModal(item));
    aksiTd.appendChild(detailBtn);

    // edit & delete hanya untuk yang punya permission
    const editBtn = document.createElement('button');
    editBtn.className = 'btn btn-edit';
    editBtn.textContent = 'Edit';
    editBtn.style.marginLeft = '6px';
    editBtn.addEventListener('click', () => openStaffModalForEdit(item));
    aksiTd.appendChild(editBtn);

    const delBtn = document.createElement('button');
    delBtn.className = 'btn btn-delete';
    delBtn.textContent = 'Hapus';
    delBtn.style.marginLeft = '6px';
    delBtn.addEventListener('click', async () => {
      if (!isAdminOrCanEdit) return alert('Hanya admin / yang diizinkan yang dapat menghapus.');
      const ok = confirm('Hapus data staff ini?');
      if (!ok) return;
      try {
        await deleteStaffFromFirestore(item.id);
        await loadAllStaff();
        alert('Data staff dihapus.');
      } catch (err) {
        alert('Gagal hapus: ' + err.message);
      }
    });
    aksiTd.appendChild(delBtn);

    tr.appendChild(aksiTd);

    tbodyEl.appendChild(tr);
  });

  // apply permissions (show/hide edit-delete)
  applyPermissionsUI();
}

/* ===========================
   MODAL / DETAIL HANDLERS
   (Simple modal open/close — adapt utk HTML modal yg kamu miliki)
   =========================== */

function openStaffModal(department = 'hatoribet') {
  if (!isAdminOrCanEdit) {
    alert('Hanya admin atau user yang diizinkan yang bisa menambah staff.');
    return;
  }
  if (!modal) {
    // fallback simple prompt
    const name = prompt('Nama Staff:');
    if (!name) return;
    // create minimal object
    addStaffToFirestore({
      name,
      department,
      createdBy: currentUser.uid,
      createdAt: serverTimestamp()
    }).then(() => loadAllStaff());
    return;
  }

  // reset form values (assumes field ids in modal exist)
  if (modalTitle) modalTitle.textContent = 'Tambah Staff Baru';
  if (staffForm) staffForm.reset();
  if (staffIdInput) staffIdInput.value = '';
  if (editModeInput) editModeInput.value = 'false';
  // mark hidden field department (if exists)
  const deptField = document.getElementById('department');
  if (deptField) deptField.value = department;

  modal.style.display = 'block';
}

function openStaffModalForEdit(item) {
  if (!isAdminOrCanEdit) {
    alert('Hanya admin atau user yang diizinkan yang bisa mengedit.');
    return;
  }
  if (!modal) {
    alert('Modal tidak ditemukan.');
    return;
  }
  if (modalTitle) modalTitle.textContent = 'Edit Staff';
  if (editModeInput) editModeInput.value = 'true';
  if (staffIdInput) staffIdInput.value = item.id;

  // isi fields (sesuaikan id field pada form staffForm)
  const setIf = (id, value) => {
    const el = document.getElementById(id);
    if (el) el.value = value ?? '';
  };

  setIf('namaStaff', item.name || '');
  setIf('inisial', item.inisial || '');
  setIf('tanggalJoin', item.tanggalJoin || '');
  setIf('idAdmin', item.idAdmin || '');
  setIf('gmail', item.gmail || item.email || '');
  setIf('bank', item.bank || '');
  setIf('noRekGaji', item.noRekGaji || '');
  setIf('namaRekGaji', item.namaRekGaji || '');
  setIf('tanggalLahir', item.tanggalLahir || '');
  setIf('gedung', item.gedung || '');
  setIf('noKamar', item.noKamar || '');
  setIf('masaKerja', item.masaKerja || '');
  setIf('department', item.department || '');
  if (modal) modal.style.display = 'block';
}

function closeStaffModal() {
  if (modal) modal.style.display = 'none';
}

function openDetailModal(item) {
  // jika tidak ada modal, gunakan alert sederhana
  if (!staffDetailContent) {
    alert(JSON.stringify(item, null, 2));
    return;
  }
  let html = `<h3>${item.name || item.namaStaff}</h3>`;
  html += `<p><strong>Email:</strong> ${item.gmail || ''}</p>`;
  html += `<p><strong>Gedung:</strong> ${item.gedung || ''}</p>`;
  html += `<p><strong>Masa Kerja:</strong> ${item.masaKerja || ''}</p>`;
  staffDetailContent.innerHTML = html;
  if (detailModal) detailModal.style.display = 'block';
}

/* ===========================
   FORM SUBMIT: tambah / edit staff
   =========================== */
async function handleStaffFormSubmit(e) {
  e.preventDefault();
  if (!isAdminOrCanEdit) {
    alert('Tidak diizinkan.');
    return;
  }
  // ambil values dari form fields (sesuaikan dengan id di modal)
  const get = id => document.getElementById(id) ? document.getElementById(id).value.trim() : '';
  const namaStaff = get('namaStaff');
  const inisial = get('inisial');
  const tanggalJoin = get('tanggalJoin');
  const idAdmin = get('idAdmin');
  const gmail = get('gmail');
  const bank = get('bank');
  const noRekGaji = get('noRekGaji');
  const namaRekGaji = get('namaRekGaji');
  const tanggalLahir = get('tanggalLahir');
  const gedung = get('gedung');
  const noKamar = get('noKamar');
  const masaKerja = get('masaKerja');
  const department = get('department') || 'hatoribet';
  const editMode = (editModeInput && editModeInput.value === 'true');
  const staffId = (staffIdInput && staffIdInput.value) || null;

  const staffObj = {
    name: namaStaff,
    inisial,
    tanggalJoin,
    idAdmin,
    gmail,
    bank,
    noRekGaji,
    namaRekGaji,
    tanggalLahir,
    gedung,
    noKamar,
    masaKerja,
    department,
    updatedAt: serverTimestamp()
  };

  try {
    if (editMode && staffId) {
      await updateStaffInFirestore(staffId, staffObj);
      alert('Data staff berhasil diperbarui.');
    } else {
      await addStaffToFirestore(staffObj);
      alert('Staff baru berhasil ditambahkan.');
    }
    closeStaffModal();
    await loadAllStaff();
  } catch (err) {
    alert('Gagal menyimpan data: ' + err.message);
  }
}

/* ===========================
   ACTIVITIES (simple local activity log saved in Firestore optional)
   (here: show placeholder / tries to fetch collection 'activities' if exists)
   =========================== */
async function loadActivities() {
  try {
    const q = query(collection(db, 'activities'));
    const snap = await getDocs(q);
    const items = snap.docs.map(d => d.data());
    if (activityList) {
      activityList.innerHTML = '';
      items.slice(0, 10).forEach(it => {
        const div = document.createElement('div');
        div.className = 'activity-item';
        div.textContent = `${it.text || JSON.stringify(it)} (${it.createdAt ? new Date(it.createdAt.seconds * 1000).toLocaleString() : ''})`;
        activityList.appendChild(div);
      });
    }
  } catch (err) {
    // tidak masalah jika collection ini belum ada
    if (activityList) activityList.innerHTML = '<p>Tidak ada aktivitas.</p>';
  }
}

/* ===========================
   UTILS
   =========================== */
function updateStats() {
  // stats sudah diupdate pada loadAllStaff; tempat ini untuk tambahan jika perlu
}

/* ===========================
   init - fallback (jika user sudah masuk dan DOM loaded)
   =========================== */
document.addEventListener('DOMContentLoaded', () => {
  // Jika auth sudah set currentUser (oleh onAuthStateChanged) maka event sudah di-init.
  // Tapi jika user info tersimpan di localStorage (fallback), kita bisa restore UI cepat:
  try {
    const cached = localStorage.getItem('currentUser');
    if (cached && !currentUser) {
      const cu = JSON.parse(cached);
      const userProfileImg = document.querySelector('.user-profile img');
      const userProfileName = document.querySelector('.user-profile span');
      if (userProfileImg) userProfileImg.src = cu.avatar || userProfileImg.src;
      if (userProfileName) userProfileName.textContent = cu.username || userProfileName.textContent;
    }
  } catch (e) { /* ignore */ }
});
